// работаем с меню
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_DISHES = 'GET_DISHES';
export const GET_MEASURES = 'GET_MEASURES';
export const UPD_DISH = 'UPD_DISH';
export const DEL_DISH = 'DEL_DISH';
export const SAGA_FETCH_CATEGORYLIST = 'SAGA_FETCH_CATEGORYLIST';
export const SAGA_FETCH_DISH = 'SAGA_FETCH_DISH';

//работаем с персоналом
export const GET_STAFF = 'GET_STAFF';
export const GET_POSITIONS = 'GET_POSITIONS';
export const UPD_STAFF = 'UPD_STAFF';
export const DEL_STAFF = 'DEL_STAFF';

// работаем с клиентами
export const GET_CLIENTS = 'GET_CLIENTS';
export const UPD_CLIENTS = 'UPD_CLIENTS';
export const DEL_CLIENTS = 'DEL_CLIENTS';

// Работа с пользователями
export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

//AT client fetch
export const SAGA_FETCH_REG = 'SAGA_FETCH_REG';
export const SAGA_FETCH_LOGIN = 'SAGA_FETCH_LOGIN';
export const SAGA_FETCH_LOGOUT = 'SAGA_FETCH_LOGOUT';

// orders
export const GET_ORDERS = 'GET_ORDERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const COMPLETE_ORDER = 'COMPLETE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const DELETE_ORDER_POSITION = 'DELETE_ORDER_POSITION';

// Работаем с резервированием
export const RESERVATION_SELECT_DATETIME = 'RESERVATION_SELECT_DATETIME';
export const RESERVATION_SELECT_HALL = 'RESERVATION_SELECT_HALL';
export const RESERVATION_SELECT_TABLE = 'RESERVATION_SELECT_TABLE';
export const RESERVATION_SET_RESERVATION = 'RESERVATION_SET_RESERVATION';
export const RESERVATION_RESET_CURRENT_SELECTION = 'RESERVATION_RESET_CURRENT_SELECTION';
export const RESERVATION_CLEAR_CURRENT = 'RESERVATION_CLEAR_CURRENT';
export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const COMPLETE_RESERVATION = 'COMPLETE_RESERVATION';
export const DELETE_RESERVATION = 'DELEDELETE_RESERVATIONTE_ORDER';
export const CANCEL_RESERVATION = 'CANCEL_RESERVATION';

// Корзина
export const CART_ADD_POSITION = 'CART_ADD_POSITION';
export const CART_REMOVE_POSITION = 'CART_REMOVE_POSITION';
export const CART_CLEAN_POSITIONS = 'CART_CLEAN_POSITIONS';
export const CART_CHANGE_QUANTITY = 'CART_CHANGE_QUANTITY';
export const CART_INCR_QUANTITY = 'CART_INCR_QUANTITY';
export const CART_DECR_QUANTITY = 'CART_DECR_QUANTITY';
export const CART_UPDATE_TOTAL = 'CART_UPDATE_TOTAL';

//Категории
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY';
export const SET_CURRENT_SUBCATEGORY = 'SET_CURRENT_SUBCATEGORY';
