export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const ADD_SUBCATEGORY = 'ADD_SUBCATEGORY';
export const CHANGE_SUBCATEGORY = 'CHANGE_SUBCATEGORY';
export const DELETE_SUBCATEGORY = 'DELETE_SUBCATEGORY';
export const SET_CURRENT_SUBCATEGORY = 'SET_CURRENT_SUBCATEGORY';

// AT categories fetch
export const SAGA_FETCH_GET_CATEGORIES = 'SAGA_FETCH_GET_CATEGORIES';
export const SAGA_FETCH_ADD_CATEGORY = 'SAGA_FETCH_ADD_CATEGORY';
export const SAGA_FETCH_CHANGE_CATEGORY = 'SAGA_FETCH_CHANGE_CATEGORY';
export const SAGA_FETCH_DELETE_CATEGORY = 'SAGA_FETCH_DELETE_CATEGORY';
export const SAGA_SET_CURRENT_CATEGORY = 'SAGA_SET_CURRENT_CATEGORY';

// AT subcategories fetch
export const SAGA_FETCH_ADD_SUBCATEGORY = 'SAGA_FETCH_ADD_SUBCATEGORY';
export const SAGA_FETCH_CHANGE_SUBCATEGORY = 'SAGA_FETCH_CHANGE_SUBCATEGORY';
export const SAGA_FETCH_DELETE_SUBCATEGORY = 'SAGA_FETCH_DELETE_SUBCATEGORY';
export const SAGA_SET_CURRENT_SUBCATEGORY = 'SAGA_SET_CURRENT_SUBCATEGORY';
